Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,10 +4,16 @@ jobs:
       - image: python:3.6                   # similar to "image" in GitLab
     steps:
       - checkout
-      - run: |                              # similar to "script" in GitLab
-          pip install -r requirements.txt
-          python manage.py check
+      - run: echo "This is a build step"
 
+  
+  test:
+    docker:
+      - image: python:3.6
+    steps:
+      - checkout
+      - run: echo "This is a test step"
+          
   bundler-audit:
     machine: true
     steps:
@@ -18,15 +24,7 @@ jobs:
       - store_artifacts:
           path: bundle-audit-output.json
           destination: bundler-audit-artifact
-
-  test:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run: |
-          pip install -r requirements.txt
-          python manage.py test taskManager
+          when: always
 
   integration:
     docker:
@@ -37,13 +35,67 @@ jobs:
           command: |
             echo "This is an integration step"
             exit 1
+          when: always 
 
   prod:
     docker:
       - image: python:3.6
+jobs:
+  build:
     steps:
       - checkout
-      - run: echo "This is a deploy step"
+      - run: echo "This is a build step"    # similar to "script" in GitLab
+
+  test:
+    steps:
+      - checkout
+      - run: echo "This is a test step"
+
+  bundler-audit:
+    machine: true
+    steps:
+      - checkout
+
+      - run: 
+          command: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json || true
+
+      - store_artifacts:
+          path: bundle-audit-output.json
+          destination: bundler-audit-artifact
+          when: always
+
+  integration:
+    steps:
+      - checkout
+      - run:
+          command: |
+            echo "This is an integration step"
+            exit 1
+          when: always                    # Even if the job fails, continue to the next stages
+
+  prod:
+    steps:
+      - checkout
+      - run: echo "This is a deploy step."
+
+workflows:
+  version: 2
+  rails:
+    jobs:
+      - build
+      - test:
+          requires:
+            - build
+      - bundler-audit:
+          requires:
+            - test
+      - integration:
+          requires:
+            - bundler-audit
+      - prod:
+          type: approval
+          requires:
+            - integration
 
 workflows:
   version: 2
